services:
  php:
    container_name: ${APP_NAME}_php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - ${PHP_PORT:-9001}:9000
    expose:
      - 9000
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/docker.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    command: sh -c "npm run dev & php-fpm"

  web:
    image: nginx:1.26.2
    container_name: ${APP_NAME}_web
    ports:
      - ${NGINX_PORT:-81}:80
    expose:
      - 80
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    platform: linux/x86_64
    image: mysql:8.0.40
    container_name: ${APP_NAME}_db
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    ports:
      - ${DB_PORT:-33061}:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    command: sh -c "chmod 644 /etc/mysql/conf.d/my.cnf && mysqld"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${APP_NAME}_phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT:-8010}:80
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      PMA_HOST: db
      MAX_EXECUTION_TIME: 3000
      MEMORY_LIMIT: 512M
      UPLOAD_LIMIT: 512M

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${APP_NAME}_mailhog
    ports:
      - ${FORWARD_MAILHOG_PORT:-1026}:1025
      - ${FORWARD_MAILHOG_DASHBOARD_PORT:-8026}:8025

  redis:
    image: redis:7.4.1
    container_name: ${APP_NAME}_redis
    ports:
      - ${REDIS_PORT:-6380}:6379
    volumes:
      - ./docker/redis/data:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: ${APP_NAME}_redisinsight
    ports:
      - ${REDISINSIGHT_PORT:-8003}:8001
    volumes:
      - ./docker/redis/insight:/db
    depends_on:
      - redis

